### ISSUE TITLE
Contact page is broken - IE browser

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#60]
Only om Explorer browser, the contact page is broken. 
There is an unnecessary space in the footer and the map is broken. 

![image](https://user-images.githubusercontent.com/26923359/35219514-a3f13134-ff7b-11e7-813f-fd95e669f5d2.png)

**Comment by MeanEYE** [comment]
Wasn't this issue fixed?

**Comment by VladimirWebDev** [comment]
Issue with footer is fixed, not deployed yet. Issue with contact page remains, although I can not reproduce it in my locale environment.

**Comment by MeanEYE** [comment]
How does it behave on your computer?

**Comment by MeanEYE** [comment]
We would need specific version for IE. Exact build and minor version number.

**Comment by VladimirWebDev** [comment]
Normally, no braking between those two div-s. As you pointed me to @MeanEYE , I get free Microsoft Windows 7 IE11 environment and Windows 10 Edge Stable 16.16299 versions. Issue with footer was present and problem was `:after` pseudo element which IE11 handles strangely since basically on inspect it shows that browser did not applied any style to element which was not correct since element was on the page and second problem was `rem` unit. I've changed it to `px` unit and apply `scaleY()` which at the end produce same result on Chrome, Firefox and IE11.. Problem with contact page was not present on IE11. Later I also get Windows10 and Edge and same result, no issue..

**Comment by talovdat** [comment]
All fixed.
